name: Deploy Backend API

on:
  push:
    branches: [main] # যদি আপনার মেইন ব্রাঞ্চ master হয়, তবে master লিখবেন

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy to Server via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: 22
          script: |
            cd /var/www/artisenleather/backend
            git reset --hard
            git pull origin main

            # মেমোরি লিমিট সেট করে ইন্সটল এবং বিল্ড
            export NODE_OPTIONS="--max-old-space-size=1024"
            npm install
            npm run build

            # PM2 দিয়ে ব্যাকএন্ড রিস্টার্ট (আপনার app এর নাম অনুযায়ী)
      
            pm2 restart api

            echo "Backend successfully updated and restarted with PM2!"
